[build]
builder = "NIXPACKS"
buildCommand = "npm --prefix ../.. run build:forecasting"

[deploy]
startCommand = "npm --prefix ../.. run start:forecasting"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
